// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package ttgstream

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type StreamFooter1 struct {
	_tab flatbuffers.Table
}

func GetRootAsStreamFooter1(buf []byte, offset flatbuffers.UOffsetT) *StreamFooter1 {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &StreamFooter1{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *StreamFooter1) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *StreamFooter1) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *StreamFooter1) Series(obj *StreamIndexedSequenceInfo, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *StreamFooter1) SeriesLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func StreamFooter1Start(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func StreamFooter1AddSeries(builder *flatbuffers.Builder, series flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(series), 0)
}
func StreamFooter1StartSeriesVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func StreamFooter1End(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
